name: snippets
description: A new social media.
publish_to: 'none'
version: 0.9.26

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter_signin_button: ^2.0.0
  flutter:
    sdk: flutter
  phone_input: ^1.0.0
  firebase_core: ^2.24.2
  shared_preferences: ^2.2.0
  home_widget: ^0.6.0
  workmanager: ^0.5.0
  async: ^2.4.1
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  cloud_functions: ^4.6.0
  http: ^1.2.1
  intl: ^0.19.0
  flutter_app_badge_control: ^0.0.1
  overlay_support: ^2.1.0
  go_router: ^14.2.1
  provider: ^6.1.2
  timezone: ^0.9.4
  drift: ^2.19.1
  drift_flutter: ^0.1.0
  share_plus: ^9.0.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.0.0
  path: ^1.8.3
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.4.1
  flutter_widgetkit: ^1.0.3
  url_launcher: ^6.3.0
  internet_connection_checker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 
  drift_dev: ^2.19.0
  build_runner: ^2.4.11


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/

flutter_native_splash:
  background_image: "assets/splash.png"