name: snippets
description: A new Flutter project.
publish_to: 'none'
version: 0.3.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter_signin_button: ^2.0.0
  flutter:
    sdk: flutter
  phone_input: ^1.0.0
  firebase_core: ^2.24.2
  shared_preferences: ^2.2.0
  async: ^2.4.1
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  cloud_functions: ^4.6.0
  http: ^1.2.1
  intl: ^0.19.0
  flutter_app_badge_control: ^0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/

